# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tc5j4jZPaQEwKBAj9No_0URFpZjqewfj
"""

#HCF(Highest common factor)
x=int(input())
y=int(input())
n=int(input("value should be greater than x,y"))
for i in range(1,n):
  if(x%i==0) and (y%i==0):
    hcf=i
print("HIGHEST COMMON FACTOR=",hcf)