# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tc5j4jZPaQEwKBAj9No_0URFpZjqewfj
"""

# convert binary to decimal
x='10100'
y=int(x,2)
print("decimal number=",y)

