# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tc5j4jZPaQEwKBAj9No_0URFpZjqewfj
"""

n=int(input())
first=int(input())
second=int(input())
i=1
print("THE FIBONACCI SERIES")
while(i<=n):
  third=first+second
  first=second
  second=third
  print(third)
  i+=1

