# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tc5j4jZPaQEwKBAj9No_0URFpZjqewfj
"""

#multlipication Table
i=1
k=int(input("enter a number"))
while(i<=10):
  y=k*i
  print(k,"*",i,"=",y)
  i+=1

